version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - echo Installing dependencies on `date`
      - npm install

  build:
    commands:
      - echo Build started on `date`
      - echo Packaging Campus Recruitment Portal

  post_build:
    commands:
      - echo Build completed on `date`

artifacts:
  files:
    - '**/*'
  discard-paths: no